# YouTube Comment & Channel Metadata Scraper v2
**Project:** SpamShield — Deteksi Spam Promosi Judi Online pada Komentar YouTube Indonesia  
**Authors:** Ricky (2702243016), Elmer Williams, Nicholas Sinclair Alfianto  
**Institution:** Bina Nusantara University  

---

### Changelog from v1
| Change | Reason |
|--------|--------|
| Added `source_channel` tracking | Analisis distribusi spam per genre channel |
| Added checkpointing (auto-save per video) | Resume jika quota habis tanpa kehilangan data |
| Added full reply fetching via `comments().list()` | v1 hanya ambil max 5 replies per thread |
| Added audit log with timestamps | Dokumentasi akademik: kapan, berapa, status |
| Added data integrity validation | Memastikan kolom konsisten sebelum export |
| Added `scrape_date` column | Reproducibility — kapan data diambil |

### Data Collection Methodology
- **API:** YouTube Data API v3  
- **Text Format:** plainText (stripped HTML, no formatting)  
- **Scope:** All top-level comments + ALL replies (not limited to 5 per thread)  
- **Channel Metadata:** Batch-fetched (50 channels/request) for efficiency  
- **Deduplication:** By video_id at load time, by comment_id at export

## 1. Setup

In [ ]:
%pip install google-api-python-client python-dotenv tqdm --quiet

In [1]:
import os
import re
import json
import time
import logging
from datetime import datetime, timezone
from pathlib import Path

import pandas as pd
from dotenv import load_dotenv
from googleapiclient.discovery import build
from googleapiclient.errors import HttpError
from tqdm.notebook import tqdm

print("Libraries imported.")

Libraries imported.

In [2]:
# Load API key
load_dotenv()
API_KEY = os.getenv('YOUTUBE_API_KEY')

if not API_KEY:
    raise ValueError(
        "YOUTUBE_API_KEY tidak ditemukan!\n"
        "Buat file .env di folder ini, isi: YOUTUBE_API_KEY=your_key_here"
    )

print(f"API Key loaded: {API_KEY[:8]}...{API_KEY[-4:]}")

API Key loaded: AIzaSyDr...xxYY

In [ ]:
# === KONFIGURASI ===
# Ganti nama output file di sini
OUTPUT_FILENAME = 'dataset_spamshield_batch2'

CONFIG = {
    'output_dir': Path('output'),
    'checkpoint_dir': Path('output/checkpoints'),
    'log_dir': Path('output/logs'),
    'request_delay': 0.3,
    'video_delay': 1.0,
    'max_results_per_page': 100,
    'channel_batch_size': 50,
    'fetch_all_replies': True,  # True = fetch semua replies, False = hanya 5 per thread
}

for d in [CONFIG['output_dir'], CONFIG['checkpoint_dir'], CONFIG['log_dir']]:
    d.mkdir(parents=True, exist_ok=True)

youtube = build('youtube', 'v3', developerKey=API_KEY)

# Setup logging
log_file = CONFIG['log_dir'] / f'scrape_{datetime.now().strftime("%Y%m%d_%H%M%S")}.log'
logging.basicConfig(
    level=logging.INFO,
    format='%(asctime)s | %(levelname)s | %(message)s',
    handlers=[
        logging.FileHandler(log_file, encoding='utf-8'),
        logging.StreamHandler()
    ]
)
logger = logging.getLogger(__name__)

SCRAPE_TIMESTAMP = datetime.now(timezone.utc).isoformat()

logger.info(f"Output: {OUTPUT_FILENAME}")
logger.info(f"Scrape timestamp: {SCRAPE_TIMESTAMP}")
logger.info(f"Config: {json.dumps({k: str(v) for k,v in CONFIG.items()}, indent=2)}")
print(f"Output: {OUTPUT_FILENAME}.csv")
print(f"Log: {log_file}")

2026-02-09 17:25:27,011 | INFO | Output: dataset_spamshield
2026-02-09 17:25:27,011 | INFO | Scrape timestamp: 2026-02-09T10:25:27.011119+00:00
2026-02-09 17:25:27,011 | INFO | Config: {
  "output_dir": "output",
  "checkpoint_dir": "output\\checkpoints",
  "log_dir": "output\\logs",
  "request_delay": "0.3",
  "video_delay": "1.0",
  "max_results_per_page": "100",
  "channel_batch_size": "50",
  "fetch_all_replies": "True"
}

Output: dataset_spamshield.csv
Log: output\logs\scrape_20260209_172527.log

## 2. Helper Functions

In [4]:
def extract_video_id(url: str) -> str | None:
    """Extract video ID (11 char) dari berbagai format YouTube URL."""
    patterns = [
        r'(?:v=)([0-9A-Za-z_-]{11})',
        r'(?:youtu\.be\/)([0-9A-Za-z_-]{11})',
        r'(?:embed\/)([0-9A-Za-z_-]{11})',
        r'(?:shorts\/)([0-9A-Za-z_-]{11})',
    ]
    for pattern in patterns:
        match = re.search(pattern, url.strip())
        if match:
            return match.group(1)
    return None


def load_video_urls(filepath: str) -> list[dict]:
    """
    Load video URLs dari file text.
    
    Format file:
    ```
    # [SOURCE_CHANNEL] Channel Name
    https://youtube.com/watch?v=xxx
    https://youtube.com/watch?v=yyy
    
    # [SOURCE_CHANNEL] Another Channel
    https://youtube.com/watch?v=zzz
    ```
    
    Lines starting with '# [TAG]' set the source_channel for subsequent URLs.
    """
    videos = []
    seen_ids = set()
    current_source = 'unknown'

    with open(filepath, 'r', encoding='utf-8') as f:
        for line_num, line in enumerate(f, 1):
            line = line.strip()
            if not line:
                continue

            # Parse source channel tag: # [MasterChef] or # [PUBG] etc
            source_match = re.match(r'^#\s*\[(.+?)\]', line)
            if source_match:
                current_source = source_match.group(1).strip()
                continue
            
            if line.startswith('#'):
                continue

            video_id = extract_video_id(line)
            if video_id and video_id not in seen_ids:
                videos.append({
                    'url': line,
                    'video_id': video_id,
                    'source_channel': current_source,
                })
                seen_ids.add(video_id)
            elif video_id in seen_ids:
                print(f"  Line {line_num}: Duplicate, skipped.")
            else:
                print(f"  Line {line_num}: Invalid URL, skipped.")

    return videos


# Quick test
test = "https://www.youtube.com/watch?v=u-zEbT8q-GQ"
print(f"Test: {test} -> {extract_video_id(test)}")

Test: https://www.youtube.com/watch?v=u-zEbT8q-GQ -> u-zEbT8q-GQ

## 3. API Functions

In [5]:
def get_video_metadata(video_id: str) -> dict | None:
    """Ambil metadata video: judul, views, likes, jumlah komentar."""
    try:
        response = youtube.videos().list(
            part='snippet,statistics',
            id=video_id
        ).execute()

        if not response.get('items'):
            logger.warning(f"Video not found: {video_id}")
            return None

        item = response['items'][0]
        snippet = item['snippet']
        stats = item['statistics']

        return {
            'video_id': video_id,
            'video_title': snippet.get('title', ''),
            'video_channel_id': snippet.get('channelId', ''),
            'video_channel_title': snippet.get('channelTitle', ''),
            'video_category_id': snippet.get('categoryId', ''),
            'video_published_at': snippet.get('publishedAt', ''),
            'video_view_count': int(stats.get('viewCount', 0)),
            'video_like_count': int(stats.get('likeCount', 0)),
            'video_comment_count': int(stats.get('commentCount', 0)),
        }

    except HttpError as e:
        logger.error(f"Video API error {video_id}: {e.resp.status}")
        return None

In [6]:
def get_channel_metadata_batch(channel_ids: list[str]) -> dict[str, dict]:
    """
    Batch-fetch channel metadata (max 50 per request).
    50 channels / 1 request = 1 quota unit (vs 50 units jika satu-satu).
    """
    DEFAULT = {
        'channel_subscriber_count': 0,
        'channel_video_count': 0,
        'channel_view_count': 0,
        'channel_created_at': '',
        'channel_description_length': 0,
        'channel_hidden_subscriber': False,
    }

    results = {}
    batch_size = CONFIG['channel_batch_size']

    for i in range(0, len(channel_ids), batch_size):
        batch = channel_ids[i:i + batch_size]

        try:
            response = youtube.channels().list(
                part='snippet,statistics',
                id=','.join(batch)
            ).execute()

            for item in response.get('items', []):
                ch_id = item['id']
                snippet = item.get('snippet', {})
                stats = item.get('statistics', {})
                hidden_subs = stats.get('hiddenSubscriberCount', False)

                results[ch_id] = {
                    'channel_subscriber_count': 0 if hidden_subs else int(stats.get('subscriberCount', 0)),
                    'channel_video_count': int(stats.get('videoCount', 0)),
                    'channel_view_count': int(stats.get('viewCount', 0)),
                    'channel_created_at': snippet.get('publishedAt', ''),
                    'channel_description_length': len(snippet.get('description', '')),
                    'channel_hidden_subscriber': hidden_subs,
                }

            time.sleep(CONFIG['request_delay'])

        except HttpError as e:
            logger.error(f"Channel batch error: {e.resp.status}")

    # Default untuk channel yang gagal
    for ch_id in channel_ids:
        if ch_id not in results:
            results[ch_id] = DEFAULT.copy()

    return results

In [7]:
def get_all_replies(parent_id: str, video_id: str) -> list[dict]:
    """
    Fetch ALL replies untuk satu comment thread.
    
    commentThreads().list() hanya return max 5 replies per thread.
    Untuk mendapatkan semua, kita perlu pakai comments().list() dengan parentId.
    """
    replies = []
    next_page_token = None

    while True:
        try:
            response = youtube.comments().list(
                part='snippet',
                parentId=parent_id,
                maxResults=100,
                pageToken=next_page_token,
                textFormat='plainText'
            ).execute()

            for item in response.get('items', []):
                rs = item['snippet']
                replies.append({
                    'comment_id': item['id'],
                    'parent_id': parent_id,
                    'is_reply': True,
                    'comment_text': rs.get('textDisplay', ''),
                    'comment_published_at': rs.get('publishedAt', ''),
                    'comment_updated_at': rs.get('updatedAt', ''),
                    'author_channel_id': rs.get('authorChannelId', {}).get('value', ''),
                    'author_display_name': rs.get('authorDisplayName', ''),
                    'like_count': int(rs.get('likeCount', 0)),
                    'reply_count': 0,
                })

            next_page_token = response.get('nextPageToken')
            if not next_page_token:
                break
            time.sleep(CONFIG['request_delay'])

        except HttpError as e:
            logger.error(f"Reply fetch error for {parent_id}: {e.resp.status}")
            break

    return replies

In [8]:
def get_video_comments(video_id: str, video_metadata: dict, source_channel: str) -> list[dict]:
    """
    Ambil SEMUA komentar + replies dari video.
    
    Strategy: 3-phase approach
    1. Ambil semua top-level comments (paginated)
    2. Untuk thread dengan >5 replies, fetch ALL replies via comments().list()
    3. Batch-fetch channel metadata untuk semua unique authors
    4. Gabungkan semua
    """
    # ===== PHASE 1: Ambil semua top-level comments =====
    raw_comments = []
    threads_needing_full_replies = []  # (parent_id, reply_count_from_api)
    author_ids = set()
    next_page_token = None

    while True:
        try:
            response = youtube.commentThreads().list(
                part='snippet,replies',
                videoId=video_id,
                maxResults=CONFIG['max_results_per_page'],
                pageToken=next_page_token,
                textFormat='plainText'
            ).execute()

            for item in response.get('items', []):
                # --- Top-level comment ---
                top = item['snippet']['topLevelComment']
                ts = top['snippet']
                author_ch_id = ts.get('authorChannelId', {}).get('value', '')
                total_replies = int(item['snippet'].get('totalReplyCount', 0))

                if author_ch_id:
                    author_ids.add(author_ch_id)

                raw_comments.append({
                    'comment_id': top['id'],
                    'parent_id': None,
                    'is_reply': False,
                    'comment_text': ts.get('textDisplay', ''),
                    'comment_published_at': ts.get('publishedAt', ''),
                    'comment_updated_at': ts.get('updatedAt', ''),
                    'author_channel_id': author_ch_id,
                    'author_display_name': ts.get('authorDisplayName', ''),
                    'like_count': int(ts.get('likeCount', 0)),
                    'reply_count': total_replies,
                })

                # --- Replies handling ---
                inline_replies = item.get('replies', {}).get('comments', [])

                if CONFIG['fetch_all_replies'] and total_replies > len(inline_replies):
                    # Thread punya lebih banyak replies daripada yang di-return inline
                    # Perlu fetch terpisah
                    threads_needing_full_replies.append(top['id'])
                else:
                    # Inline replies sudah cukup (<=5 replies)
                    for reply in inline_replies:
                        rs = reply['snippet']
                        reply_ch_id = rs.get('authorChannelId', {}).get('value', '')
                        if reply_ch_id:
                            author_ids.add(reply_ch_id)

                        raw_comments.append({
                            'comment_id': reply['id'],
                            'parent_id': top['id'],
                            'is_reply': True,
                            'comment_text': rs.get('textDisplay', ''),
                            'comment_published_at': rs.get('publishedAt', ''),
                            'comment_updated_at': rs.get('updatedAt', ''),
                            'author_channel_id': reply_ch_id,
                            'author_display_name': rs.get('authorDisplayName', ''),
                            'like_count': int(rs.get('likeCount', 0)),
                            'reply_count': 0,
                        })

            next_page_token = response.get('nextPageToken')
            if not next_page_token:
                break
            time.sleep(CONFIG['request_delay'])

        except HttpError as e:
            if e.resp.status == 403:
                if 'commentsDisabled' in str(e):
                    logger.warning(f"Comments disabled: {video_id}")
                elif 'quotaExceeded' in str(e):
                    logger.error("Quota exceeded!")
                    raise
                else:
                    logger.warning(f"Forbidden: {video_id}")
            else:
                logger.error(f"API Error: {e.resp.status}")
            break

    # ===== PHASE 1.5: Fetch full replies for threads that need it =====
    if threads_needing_full_replies:
        tqdm.write(f"    -> Fetching full replies for {len(threads_needing_full_replies)} threads...")
        for parent_id in threads_needing_full_replies:
            full_replies = get_all_replies(parent_id, video_id)
            for r in full_replies:
                if r['author_channel_id']:
                    author_ids.add(r['author_channel_id'])
            raw_comments.extend(full_replies)

    if not raw_comments:
        return []

    # ===== PHASE 2: Batch-fetch channel metadata =====
    unique_authors = list(author_ids)
    tqdm.write(f"    -> {len(raw_comments)} comments, {len(unique_authors)} unique authors")

    channel_meta_map = get_channel_metadata_batch(unique_authors)

    # ===== PHASE 3: Gabungkan semua =====
    DEFAULT_CH = {
        'channel_subscriber_count': 0,
        'channel_video_count': 0,
        'channel_view_count': 0,
        'channel_created_at': '',
        'channel_description_length': 0,
        'channel_hidden_subscriber': False,
    }

    final = []
    for c in raw_comments:
        ch_meta = channel_meta_map.get(c['author_channel_id'], DEFAULT_CH)
        final.append({
            **c,
            **ch_meta,
            **video_metadata,
            'source_channel': source_channel,
            'scrape_date': SCRAPE_TIMESTAMP,
        })

    return final

## 4. Main Scraper (with Checkpointing)

In [9]:
def load_checkpoint() -> set:
    """Load video IDs yang sudah berhasil di-scrape dari checkpoint files."""
    done = set()
    for f in CONFIG['checkpoint_dir'].glob('*.csv'):
        try:
            df = pd.read_csv(f, usecols=['video_id'], encoding='utf-8-sig')
            done.update(df['video_id'].unique())
        except Exception:
            pass
    return done


def save_checkpoint(comments: list[dict], video_id: str):
    """Save komentar satu video sebagai checkpoint file."""
    if not comments:
        return
    filepath = CONFIG['checkpoint_dir'] / f'cp_{video_id}.csv'
    pd.DataFrame(comments).to_csv(filepath, index=False, encoding='utf-8-sig')


def scrape_videos(video_list: list[dict], resume: bool = True) -> tuple[pd.DataFrame, pd.DataFrame]:
    """
    Scrape semua video dalam list.
    
    - resume=True: skip video yang sudah ada di checkpoint
    - Auto-save setiap video selesai
    - Quota exceeded -> save progress, bisa dilanjut nanti
    """
    already_done = load_checkpoint() if resume else set()
    if already_done:
        logger.info(f"Resuming: {len(already_done)} videos already scraped")

    all_comments = []
    video_stats = []

    for idx, video in enumerate(tqdm(video_list, desc="Scraping")):
        video_id = video['video_id']
        source_channel = video.get('source_channel', 'unknown')

        # Skip if already done
        if video_id in already_done:
            tqdm.write(f"  [SKIP] {video_id} (already scraped)")
            continue

        # Step 1: Video metadata
        metadata = get_video_metadata(video_id)
        if not metadata:
            video_stats.append({
                'video_id': video_id, 'source_channel': source_channel,
                'status': 'error_metadata', 'comments_scraped': 0
            })
            continue

        # Step 2: Comments + channel metadata
        try:
            comments = get_video_comments(video_id, metadata, source_channel)

            # Checkpoint: save per video
            save_checkpoint(comments, video_id)

            video_stats.append({
                'video_id': video_id,
                'video_title': metadata['video_title'],
                'video_channel_title': metadata['video_channel_title'],
                'source_channel': source_channel,
                'video_comment_count_api': metadata['video_comment_count'],
                'comments_scraped': len(comments),
                'status': 'success'
            })

            all_comments.extend(comments)
            logger.info(f"[{idx+1}/{len(video_list)}] {metadata['video_title'][:50]}... -> {len(comments)} comments")
            tqdm.write(f"  [{idx+1}/{len(video_list)}] {metadata['video_title'][:50]}... -> {len(comments)}")

        except HttpError as e:
            if 'quotaExceeded' in str(e):
                logger.error("QUOTA EXCEEDED! Saving progress. Run lagi besok untuk lanjut.")
                print("\nQuota exceeded! Progress saved. Run lagi besok untuk lanjut.")
                break
            video_stats.append({
                'video_id': video_id, 'source_channel': source_channel,
                'status': 'error_comments', 'comments_scraped': 0
            })

        time.sleep(CONFIG['video_delay'])

    # Jika resume, merge dengan checkpoint data
    if resume and already_done:
        logger.info("Merging with checkpoint data...")
        for f in CONFIG['checkpoint_dir'].glob('*.csv'):
            try:
                cp_df = pd.read_csv(f, encoding='utf-8-sig')
                all_comments.extend(cp_df.to_dict('records'))
            except Exception:
                pass

    return pd.DataFrame(all_comments), pd.DataFrame(video_stats)

## 5. Load URLs & Run

In [10]:
# Load video URLs
# Format file video_urls.txt:
#
# # [MasterChef] MasterChef Indonesia
# https://youtube.com/watch?v=xxx
# https://youtube.com/watch?v=yyy
#
# # [PUBG] PUBG Mobile Indonesia
# https://youtube.com/watch?v=zzz

VIDEO_URL_FILE = 'video_urls.txt'

if not Path(VIDEO_URL_FILE).exists():
    raise FileNotFoundError(
        f"File '{VIDEO_URL_FILE}' tidak ditemukan!\n"
        f"Buat file tersebut, isi dengan URL YouTube (satu per baris)."
    )

video_list = load_video_urls(VIDEO_URL_FILE)
print(f"Loaded {len(video_list)} unique videos")

# Show per-source summary
from collections import Counter
source_counts = Counter(v['source_channel'] for v in video_list)
print(f"\nPer source:")
for source, count in source_counts.most_common():
    print(f"  [{source}]: {count} videos")

Loaded 106 unique videos

Per source:
  [XIN]: 25 videos
  [ML]: 21 videos
  [JebreetMedia]: 19 videos
  [MasterChef]: 14 videos
  [PUBG]: 10 videos
  [FrostDiamond]: 10 videos
  [FerryIrwandi]: 6 videos
  [RaymondChin]: 1 videos

In [11]:
# === RUN SCRAPER ===
print(f"Starting scraper for {len(video_list)} videos...")
print("=" * 60)

start_time = time.time()
comments_df, stats_df = scrape_videos(video_list, resume=True)
elapsed = time.time() - start_time

print("=" * 60)
print(f"Done in {elapsed:.1f}s ({elapsed/60:.1f} min)")

Starting scraper for 106 videos...
============================================================

Scraping:   0%|          | 0/106 [00:00<?, ?it/s]

    -> Fetching full replies for 2 threads...
    -> 95 comments, 85 unique authors

2026-02-09 17:25:55,320 | INFO | [1/106] Hero Spotlight | Kimmy | Hoverjet Outrider | Mobil... -> 95 comments

  [1/106] Hero Spotlight | Kimmy | Hoverjet Outrider | Mobil... -> 95
    -> Fetching full replies for 1 threads...
    -> 88 comments, 75 unique authors

2026-02-09 17:25:57,625 | INFO | [2/106] MLBB × NARUTO | Pratinjau Konten Kustom | Mobile L... -> 88 comments

  [2/106] MLBB × NARUTO | Pratinjau Konten Kustom | Mobile L... -> 88
    -> Fetching full replies for 1 threads...
    -> 85 comments, 83 unique authors

2026-02-09 17:25:59,894 | INFO | [3/106] 🔴 LIVE | MPL ID S15 | Regular Season Hari 3 Minggu... -> 85 comments

  [3/106] 🔴 LIVE | MPL ID S15 | Regular Season Hari 3 Minggu... -> 85
    -> 44 comments, 42 unique authors

2026-02-09 17:26:01,489 | INFO | [4/106] 🔴 LIVE | MPL ID S15 | Regular Season Hari 1 Minggu... -> 44 comments

  [4/106] 🔴 LIVE | MPL ID S15 | Regular Season Hari 1 Minggu... -> 44
    -> 15 comments, 12 unique authors

2026-02-09 17:26:03,052 | INFO | [5/106] 🔴LIVE | MDL ID S11 | Progressive Round | Hari 1 Pu... -> 15 comments

  [5/106] 🔴LIVE | MDL ID S11 | Progressive Round | Hari 1 Pu... -> 15
    -> 53 comments, 52 unique authors

2026-02-09 17:26:05,338 | INFO | [6/106] MLBB x OPPO Smooth Legends Cup | APAC Grand Finals... -> 53 comments

  [6/106] MLBB x OPPO Smooth Legends Cup | APAC Grand Finals... -> 53
    -> 52 comments, 48 unique authors

2026-02-09 17:26:08,414 | INFO | [7/106] 🔴 LIVE | MPL ID S15 | Regular Season Hari 3 Minggu... -> 52 comments

  [7/106] 🔴 LIVE | MPL ID S15 | Regular Season Hari 3 Minggu... -> 52
    -> 82 comments, 78 unique authors

2026-02-09 17:26:10,678 | INFO | [8/106] 🔴 LIVE | MPL ID S15 | Regular Season Hari 2 Minggu... -> 82 comments

  [8/106] 🔴 LIVE | MPL ID S15 | Regular Season Hari 2 Minggu... -> 82
    -> 103 comments, 102 unique authors

2026-02-09 17:26:13,324 | INFO | [9/106] 🔴 LIVE | MPL ID S15 | Regular Season Hari 1 Minggu... -> 103 comments

  [9/106] 🔴 LIVE | MPL ID S15 | Regular Season Hari 1 Minggu... -> 103
    -> 52 comments, 48 unique authors

2026-02-09 17:26:14,944 | INFO | [10/106] 🔴 LIVE | MPL ID S15 | Regular Season Hari 3 Minggu... -> 52 comments

  [10/106] 🔴 LIVE | MPL ID S15 | Regular Season Hari 3 Minggu... -> 52
    -> Fetching full replies for 1 threads...
    -> 119 comments, 111 unique authors

2026-02-09 17:26:17,881 | INFO | [11/106] 🔴 LIVE | MPL ID S15 | Regular Season Hari 2 Minggu... -> 119 comments

  [11/106] 🔴 LIVE | MPL ID S15 | Regular Season Hari 2 Minggu... -> 119
    -> 89 comments, 86 unique authors

2026-02-09 17:26:20,111 | INFO | [12/106] 🔴 LIVE | MPL ID S15 | Regular Season Hari 1 Minggu... -> 89 comments

  [12/106] 🔴 LIVE | MPL ID S15 | Regular Season Hari 1 Minggu... -> 89
    -> 40 comments, 38 unique authors

2026-02-09 17:26:21,973 | INFO | [13/106] MLBB x OPPO Smooth Legends Cup | APAC Grand Finals... -> 40 comments

  [13/106] MLBB x OPPO Smooth Legends Cup | APAC Grand Finals... -> 40
    -> 25 comments, 24 unique authors

2026-02-09 17:26:23,562 | INFO | [14/106] MLBB x OPPO Smooth Legends Cup | APAC Grand Finals... -> 25 comments

  [14/106] MLBB x OPPO Smooth Legends Cup | APAC Grand Finals... -> 25
    -> 66 comments, 57 unique authors

2026-02-09 17:26:25,687 | INFO | [15/106] MLBB x OPPO Smooth Legends Cup | APAC Grand Finals... -> 66 comments

  [15/106] MLBB x OPPO Smooth Legends Cup | APAC Grand Finals... -> 66
    -> 25 comments, 25 unique authors

2026-02-09 17:26:27,303 | INFO | [16/106] 🔴LIVE | MDL ID S11 | Progressive Round | Hari 3 Pu... -> 25 comments

  [16/106] 🔴LIVE | MDL ID S11 | Progressive Round | Hari 3 Pu... -> 25
    -> 22 comments, 22 unique authors

2026-02-09 17:26:28,856 | INFO | [17/106] 🔴LIVE | MDL ID S11 | Regular Season | Minggu 2 Har... -> 22 comments

  [17/106] 🔴LIVE | MDL ID S11 | Regular Season | Minggu 2 Har... -> 22
    -> Fetching full replies for 6 threads...
    -> 280 comments, 209 unique authors

2026-02-09 17:26:33,279 | INFO | [18/106] Demonstrasi Gaara | MLBB × NARUTO | Mobile Legends... -> 280 comments

  [18/106] Demonstrasi Gaara | MLBB × NARUTO | Mobile Legends... -> 280
    -> Fetching full replies for 3 threads...
    -> 324 comments, 300 unique authors

2026-02-09 17:26:38,512 | INFO | [19/106] Tekad Api Menyala Kembali | MLBB × NARUTO | Mobile... -> 324 comments

  [19/106] Tekad Api Menyala Kembali | MLBB × NARUTO | Mobile... -> 324
    -> Fetching full replies for 1 threads...
    -> 28 comments, 27 unique authors

2026-02-09 17:26:40,282 | INFO | [20/106] Perbandingan Build Melisa | Mobile Legends: Bang B... -> 28 comments

  [20/106] Perbandingan Build Melisa | Mobile Legends: Bang B... -> 28
    -> 60 comments, 59 unique authors

2026-02-09 17:26:42,294 | INFO | [21/106] Gameplay Joy | Mobile Legends: Bang Bang Indonesia... -> 60 comments

  [21/106] Gameplay Joy | Mobile Legends: Bang Bang Indonesia... -> 60
    -> Fetching full replies for 2 threads...
    -> 41 comments, 34 unique authors

2026-02-09 17:26:44,164 | INFO | [22/106] Pemenang Royal Rumble Buat Tantangan Terbuka! I PU... -> 41 comments

  [22/106] Pemenang Royal Rumble Buat Tantangan Terbuka! I PU... -> 41
    -> Fetching full replies for 1 threads...
    -> 42 comments, 35 unique authors

2026-02-09 17:26:45,959 | INFO | [23/106] [ID] PUBG MOBILE: The Royal Rumble | SEA SHOWMATCH... -> 42 comments

  [23/106] [ID] PUBG MOBILE: The Royal Rumble | SEA SHOWMATCH... -> 42
    -> 21 comments, 20 unique authors

2026-02-09 17:26:47,686 | INFO | [24/106] GRAND FINAL JAWARA CUP ROAD TO PMNC SUMMER 2025!... -> 21 comments

  [24/106] GRAND FINAL JAWARA CUP ROAD TO PMNC SUMMER 2025!... -> 21
    -> 22 comments, 22 unique authors

2026-02-09 17:26:49,340 | INFO | [25/106] [ID] 2025 PMGO Uzbekistan Prelims | Day 2 | PUBG M... -> 22 comments

  [25/106] [ID] 2025 PMGO Uzbekistan Prelims | Day 2 | PUBG M... -> 22
    -> 39 comments, 39 unique authors

2026-02-09 17:26:50,896 | INFO | [26/106] Grebek PUBG MOBILE Bareng PAK AMBARITA... -> 39 comments

  [26/106] Grebek PUBG MOBILE Bareng PAK AMBARITA... -> 39
    -> Fetching full replies for 1 threads...
    -> 83 comments, 74 unique authors

2026-02-09 17:26:52,962 | INFO | [27/106] ANNIVERSARY PUBG MOBILE - DAY 1 🏆🔥... -> 83 comments

  [27/106] ANNIVERSARY PUBG MOBILE - DAY 1 🏆🔥... -> 83
    -> Fetching full replies for 6 threads...
    -> 206 comments, 176 unique authors

2026-02-09 17:26:59,255 | INFO | [28/106] [ID] 2025 PMSL SEA GFD3 | Spring | Saatnya Tentuka... -> 206 comments

  [28/106] [ID] 2025 PMSL SEA GFD3 | Spring | Saatnya Tentuka... -> 206
    -> Fetching full replies for 2 threads...
    -> 93 comments, 74 unique authors

2026-02-09 17:27:01,500 | INFO | [29/106] [ID] 2025 PMSL SEA GFD2 | Spring | Semakin Tegang,... -> 93 comments

  [29/106] [ID] 2025 PMSL SEA GFD2 | Spring | Semakin Tegang,... -> 93
    -> Fetching full replies for 3 threads...
    -> 109 comments, 100 unique authors

2026-02-09 17:27:07,349 | INFO | [30/106] [ID] 2025 PMSL SEA GFD1 | Spring | Hari pertama, S... -> 109 comments

  [30/106] [ID] 2025 PMSL SEA GFD1 | Spring | Hari pertama, S... -> 109
    -> 10 comments, 9 unique authors

2026-02-09 17:27:08,875 | INFO | [31/106] Nonton Kembang Api di PUBG MOBILE INDONESIA... -> 10 comments

  [31/106] Nonton Kembang Api di PUBG MOBILE INDONESIA... -> 10
    -> Fetching full replies for 8 threads...
    -> 933 comments, 824 unique authors

2026-02-09 17:27:22,145 | INFO | [32/106] Sosok "Pembunuh" Tupperware Setelah 33 Tahun di In... -> 933 comments

  [32/106] Sosok "Pembunuh" Tupperware Setelah 33 Tahun di In... -> 933
    -> 741 comments, 669 unique authors

2026-02-09 17:27:32,617 | INFO | [33/106] SERAM! CCTV MEREKAM ANAK SD KEPALA BABI DI RUANG T... -> 741 comments

  [33/106] SERAM! CCTV MEREKAM ANAK SD KEPALA BABI DI RUANG T... -> 741
    -> Fetching full replies for 2 threads...
    -> 349 comments, 321 unique authors

2026-02-09 17:27:38,939 | INFO | [34/106] GINI RASANYA SEHARIAN MENJADI CHOMPER TANAMAN DI P... -> 349 comments

  [34/106] GINI RASANYA SEHARIAN MENJADI CHOMPER TANAMAN DI P... -> 349
    -> Fetching full replies for 2 threads...
    -> 356 comments, 316 unique authors

2026-02-09 17:27:51,215 | INFO | [35/106] KITA BERTAHAN HIDUP DALAM LINGKARAN INI MELAWAN 10... -> 356 comments

  [35/106] KITA BERTAHAN HIDUP DALAM LINGKARAN INI MELAWAN 10... -> 356
    -> Fetching full replies for 5 threads...
    -> 829 comments, 716 unique authors

2026-02-09 17:28:03,245 | INFO | [36/106] MERINDING!!! AKU COBAIN PENDETEKSI HANTU DI RUMAH ... -> 829 comments

  [36/106] MERINDING!!! AKU COBAIN PENDETEKSI HANTU DI RUMAH ... -> 829
    -> Fetching full replies for 3 threads...
    -> 817 comments, 686 unique authors

2026-02-09 17:28:14,987 | INFO | [37/106] DRONE BERHASIL MENANGKAP ANAK SD KEPALA BABI DI AM... -> 817 comments

  [37/106] DRONE BERHASIL MENANGKAP ANAK SD KEPALA BABI DI AM... -> 817
    -> 339 comments, 311 unique authors

2026-02-09 17:28:20,961 | INFO | [38/106] 10 TAHUN GA MAIN PLANT VS ZOMBIE, SEKARANG UDAH 4D... -> 339 comments

  [38/106] 10 TAHUN GA MAIN PLANT VS ZOMBIE, SEKARANG UDAH 4D... -> 339
    -> 305 comments, 264 unique authors

2026-02-09 17:28:26,029 | INFO | [39/106] Dikatain Petinju Gendut DONTOL Sama Cewe Cantik!!!... -> 305 comments

  [39/106] Dikatain Petinju Gendut DONTOL Sama Cewe Cantik!!!... -> 305
    -> Fetching full replies for 1 threads...
    -> 524 comments, 477 unique authors

2026-02-09 17:28:34,419 | INFO | [40/106] Kita Kabur Dari PENJARA Tower Diburu DONTOL Dari R... -> 524 comments

  [40/106] Kita Kabur Dari PENJARA Tower Diburu DONTOL Dari R... -> 524
    -> Fetching full replies for 4 threads...
    -> 869 comments, 626 unique authors

2026-02-09 17:28:46,294 | INFO | [41/106] SERAM! MAIN PETAK UMPET PAS KLIWON, TUNG TUNG SAHU... -> 869 comments

  [41/106] SERAM! MAIN PETAK UMPET PAS KLIWON, TUNG TUNG SAHU... -> 869
    -> Fetching full replies for 2 threads...
    -> 984 comments, 795 unique authors

2026-02-09 17:28:59,796 | INFO | [42/106] TAMAT!!! BIKIN KERETA API FULL BERLAPIS EMAS, ZOMB... -> 984 comments

  [42/106] TAMAT!!! BIKIN KERETA API FULL BERLAPIS EMAS, ZOMB... -> 984
    -> Fetching full replies for 58 threads...
    -> 9639 comments, 7958 unique authors

2026-02-09 17:31:01,866 | INFO | [43/106] Generasi Muda, Bonus Demografi dan Masa Depan Indo... -> 9639 comments

  [43/106] Generasi Muda, Bonus Demografi dan Masa Depan Indo... -> 9639
    -> Fetching full replies for 34 threads...
    -> 2162 comments, 1622 unique authors

2026-02-09 17:31:26,497 | INFO | [44/106] Elon Musk Ubah Twitter Jadi Tempat yang Berbahaya!... -> 2162 comments

  [44/106] Elon Musk Ubah Twitter Jadi Tempat yang Berbahaya!... -> 2162
    -> Fetching full replies for 43 threads...
    -> 5539 comments, 4418 unique authors

2026-02-09 17:32:36,049 | INFO | [45/106] Catatan Demonstran Untuk Prabowo Subianto... -> 5539 comments

  [45/106] Catatan Demonstran Untuk Prabowo Subianto... -> 5539
    -> Fetching full replies for 28 threads...
    -> 3660 comments, 3047 unique authors

2026-02-09 17:33:23,964 | INFO | [46/106] KEJAKSAAN RI Menuju Power Absolut... -> 3660 comments

  [46/106] KEJAKSAAN RI Menuju Power Absolut... -> 3660
    -> Fetching full replies for 5 threads...
    -> 852 comments, 746 unique authors

2026-02-09 17:33:38,155 | INFO | [47/106] Range Rover untuk Bapak... -> 852 comments

  [47/106] Range Rover untuk Bapak... -> 852
    -> Fetching full replies for 24 threads...
    -> 3085 comments, 2599 unique authors

2026-02-09 17:34:19,423 | INFO | [48/106] MAKAN BERGIZI GRATIS | MBG... -> 3085 comments

  [48/106] MAKAN BERGIZI GRATIS | MBG... -> 3085
    -> 71 comments, 64 unique authors

2026-02-09 17:34:21,369 | INFO | [49/106] MANCHESTER UNITED KEMBALI JADI HIBURAN AKHIR PEKAN... -> 71 comments

  [49/106] MANCHESTER UNITED KEMBALI JADI HIBURAN AKHIR PEKAN... -> 71
    -> Fetching full replies for 1 threads...
    -> 99 comments, 90 unique authors

2026-02-09 17:34:23,588 | INFO | [50/106] ⁠LIVERPOOL MASIH BUTUH TAA? ARSENAL BERUNTUNG PUNY... -> 99 comments

  [50/106] ⁠LIVERPOOL MASIH BUTUH TAA? ARSENAL BERUNTUNG PUNY... -> 99
    -> Fetching full replies for 3 threads...
    -> 95 comments, 78 unique authors

2026-02-09 17:34:26,009 | INFO | [51/106] BARCELONA NGAJARIN DEK MADRID REMONTADA... -> 95 comments

  [51/106] BARCELONA NGAJARIN DEK MADRID REMONTADA... -> 95
    -> 30 comments, 30 unique authors

2026-02-09 17:34:27,537 | INFO | [52/106] MENDING PAKE MANAGEMENT ARTIS APA URUS SENDIRI AJA... -> 30 comments

  [52/106] MENDING PAKE MANAGEMENT ARTIS APA URUS SENDIRI AJA... -> 30
    -> Fetching full replies for 2 threads...
    -> 80 comments, 66 unique authors

2026-02-09 17:34:29,708 | INFO | [53/106] REMONTADA: REAL MADRID OUT DADAH! | KPI Eps 24... -> 80 comments

  [53/106] REMONTADA: REAL MADRID OUT DADAH! | KPI Eps 24... -> 80
    -> Fetching full replies for 1 threads...
    -> 176 comments, 164 unique authors

2026-02-09 17:34:33,178 | INFO | [54/106] NOPEK NOVIAN: LUCU AJA GAK CUKUP, LPM HARUS WAR WE... -> 176 comments

  [54/106] NOPEK NOVIAN: LUCU AJA GAK CUKUP, LPM HARUS WAR WE... -> 176
    -> Fetching full replies for 5 threads...
    -> 209 comments, 172 unique authors

2026-02-09 17:34:37,180 | INFO | [55/106] MAN UNITED & LIVERPOOL BAGAIKAN LANGIT & BUMI! - D... -> 209 comments

  [55/106] MAN UNITED & LIVERPOOL BAGAIKAN LANGIT & BUMI! - D... -> 209
    -> Fetching full replies for 7 threads...
    -> 230 comments, 177 unique authors

2026-02-09 17:34:42,327 | INFO | [56/106] ARSENAL, BARCELONA, INTER MILAN DAN PSG SIAPA PAHL... -> 230 comments

  [56/106] ARSENAL, BARCELONA, INTER MILAN DAN PSG SIAPA PAHL... -> 230
    -> Fetching full replies for 9 threads...
    -> 356 comments, 279 unique authors

2026-02-09 17:34:47,995 | INFO | [57/106] INTER MILAN SOLID BAYERN MUNCHEN MASIH KENA KUTUKA... -> 356 comments

  [57/106] INTER MILAN SOLID BAYERN MUNCHEN MASIH KENA KUTUKA... -> 356
    -> Fetching full replies for 6 threads...
    -> 302 comments, 233 unique authors

2026-02-09 17:34:52,684 | INFO | [58/106] ARSENAL MENANG MUDAH DARI MADRID, MBAPPE TERNYATA ... -> 302 comments

  [58/106] ARSENAL MENANG MUDAH DARI MADRID, MBAPPE TERNYATA ... -> 302
    -> 19 comments, 16 unique authors

2026-02-09 17:34:54,280 | INFO | [59/106] MAN UNITED MELTDOWN: RUBEN AMORIM SURRENDER AT PRE... -> 19 comments

  [59/106] MAN UNITED MELTDOWN: RUBEN AMORIM SURRENDER AT PRE... -> 19
    -> 27 comments, 27 unique authors

2026-02-09 17:34:55,917 | INFO | [60/106] LIVERPOOL OTW WIN THE PREMIER LEAGUE - DPI ENGLISH... -> 27 comments

  [60/106] LIVERPOOL OTW WIN THE PREMIER LEAGUE - DPI ENGLISH... -> 27
    -> Fetching full replies for 1 threads...
    -> 70 comments, 57 unique authors

2026-02-09 17:34:58,075 | INFO | [61/106] ⁠BARCELONA NYARIS DIPULANGKAN DORTMUND... -> 70 comments

  [61/106] ⁠BARCELONA NYARIS DIPULANGKAN DORTMUND... -> 70
    -> Fetching full replies for 2 threads...
    -> 206 comments, 167 unique authors

2026-02-09 17:35:01,545 | INFO | [62/106] REAL MADRID VS ARSENAL BEGITU MUDAH DIPREDIKSI... -> 206 comments

  [62/106] REAL MADRID VS ARSENAL BEGITU MUDAH DIPREDIKSI... -> 206
    -> Fetching full replies for 1 threads...
    -> 70 comments, 62 unique authors

2026-02-09 17:35:03,744 | INFO | [63/106] TIMNAS U17 DAPAT PELAJARAN BERHARGA MENUJU PIALA D... -> 70 comments

  [63/106] TIMNAS U17 DAPAT PELAJARAN BERHARGA MENUJU PIALA D... -> 70
    -> 82 comments, 72 unique authors

2026-02-09 17:35:05,804 | INFO | [64/106] GAK SEMUA PUNDIT TAU TRIVIA SEPAKBOLA INI BUKTINYA... -> 82 comments

  [64/106] GAK SEMUA PUNDIT TAU TRIVIA SEPAKBOLA INI BUKTINYA... -> 82
    -> 36 comments, 35 unique authors

2026-02-09 17:35:07,364 | INFO | [65/106] PERSONA ANAK PUNK SAMPE KASIR MINI MARKET IKUT AUD... -> 36 comments

  [65/106] PERSONA ANAK PUNK SAMPE KASIR MINI MARKET IKUT AUD... -> 36
    -> 164 comments, 157 unique authors

2026-02-09 17:35:11,267 | INFO | [66/106] SEMPURNA! TIMNAS INDONESIA U-17 SAPU BERSIH KEMENA... -> 164 comments

  [66/106] SEMPURNA! TIMNAS INDONESIA U-17 SAPU BERSIH KEMENA... -> 164
    -> Fetching full replies for 3 threads...
    -> 200 comments, 164 unique authors

2026-02-09 17:35:14,825 | INFO | [67/106] KEMENANGAN SUPER NYAMAN BARCELONA DI UCL, GINI LHO... -> 200 comments

  [67/106] KEMENANGAN SUPER NYAMAN BARCELONA DI UCL, GINI LHO... -> 200
    -> Fetching full replies for 9 threads...
    -> 1434 comments, 1232 unique authors

2026-02-09 17:35:34,667 | INFO | [68/106] Azwar Pukul Panci, Ini Dia Alasannya! | Galeri 13 ... -> 1434 comments

  [68/106] Azwar Pukul Panci, Ini Dia Alasannya! | Galeri 13 ... -> 1434
    -> Fetching full replies for 25 threads...
    -> 1433 comments, 1154 unique authors

2026-02-09 17:35:57,312 | INFO | [69/106] Pamernya Berhasil! Hesti Suka Nasi Uduk Buatan Man... -> 1433 comments

  [69/106] Pamernya Berhasil! Hesti Suka Nasi Uduk Buatan Man... -> 1433
    -> Fetching full replies for 9 threads...
    -> 853 comments, 757 unique authors

2026-02-09 17:36:09,739 | INFO | [70/106] Azwar Masak BEBEK BACEM Bikin Ribet Sendiri | Gale... -> 853 comments

  [70/106] Azwar Masak BEBEK BACEM Bikin Ribet Sendiri | Gale... -> 853
    -> Fetching full replies for 14 threads...
    -> 1237 comments, 1093 unique authors

2026-02-09 17:36:27,950 | INFO | [71/106] Hesti Tantang All Peserta Masak LENCAK | Galeri 13... -> 1237 comments

  [71/106] Hesti Tantang All Peserta Masak LENCAK | Galeri 13... -> 1237
    -> Fetching full replies for 43 threads...
    -> 3506 comments, 2746 unique authors

2026-02-09 17:37:12,301 | INFO | [72/106] Chef Juna Berikan Pesan Moral Dengan Sangat Lantan... -> 3506 comments

  [72/106] Chef Juna Berikan Pesan Moral Dengan Sangat Lantan... -> 3506
    -> Fetching full replies for 17 threads...
    -> 838 comments, 707 unique authors

2026-02-09 17:37:23,757 | INFO | [73/106] Jane Dapat Masukan Dari Chef Renata Cara Berkompet... -> 838 comments

  [73/106] Jane Dapat Masukan Dari Chef Renata Cara Berkompet... -> 838
    -> Fetching full replies for 19 threads...
    -> 1649 comments, 1383 unique authors

2026-02-09 17:37:45,319 | INFO | [74/106] Chef Rudy Sampai Mantau Langsung Yang Dibuat Vini ... -> 1649 comments

  [74/106] Chef Rudy Sampai Mantau Langsung Yang Dibuat Vini ... -> 1649
    -> Fetching full replies for 24 threads...
    -> 1601 comments, 1319 unique authors

2026-02-09 17:38:07,677 | INFO | [75/106] Jane Menangis Mendengar Perkataan Malrani | OFFSIT... -> 1601 comments

  [75/106] Jane Menangis Mendengar Perkataan Malrani | OFFSIT... -> 1601
    -> Fetching full replies for 18 threads...
    -> 1369 comments, 1185 unique authors

2026-02-09 17:38:28,730 | INFO | [76/106] MENEGANGKAN! Saatnya Untuk Voting | OFFSITE 2 (5/9... -> 1369 comments

  [76/106] MENEGANGKAN! Saatnya Untuk Voting | OFFSITE 2 (5/9... -> 1369
    -> Fetching full replies for 24 threads...
    -> 1923 comments, 1483 unique authors

2026-02-09 17:38:51,904 | INFO | [77/106] VINZ PANIK! Akibat Kebingungan Kentang Vinz Jatuh ... -> 1923 comments

  [77/106] VINZ PANIK! Akibat Kebingungan Kentang Vinz Jatuh ... -> 1923
    -> Fetching full replies for 12 threads...
    -> 714 comments, 564 unique authors

2026-02-09 17:39:03,000 | INFO | [78/106] Kedua Tim Dibikin Pusing Karena Arang Gak Mau Meny... -> 714 comments

  [78/106] Kedua Tim Dibikin Pusing Karena Arang Gak Mau Meny... -> 714
    -> Fetching full replies for 14 threads...
    -> 1061 comments, 864 unique authors

2026-02-09 17:39:16,473 | INFO | [79/106] Makin Chaos! Ternyata Masakannya Masih Kurang Asin... -> 1061 comments

  [79/106] Makin Chaos! Ternyata Masakannya Masih Kurang Asin... -> 1061
    -> Fetching full replies for 12 threads...
    -> 1524 comments, 1360 unique authors

2026-02-09 17:39:38,551 | INFO | [80/106] Tim Merah & Tim Biru Ditantang Masak Untuk Anggota... -> 1524 comments

  [80/106] Tim Merah & Tim Biru Ditantang Masak Untuk Anggota... -> 1524
    -> Fetching full replies for 22 threads...
    -> 1792 comments, 1455 unique authors

2026-02-09 17:40:01,992 | INFO | [81/106] Sebuah Privilege Kali Ini Tidak Disia-Siakan Oleh ... -> 1792 comments

  [81/106] Sebuah Privilege Kali Ini Tidak Disia-Siakan Oleh ... -> 1792
    -> 97 comments, 97 unique authors

2026-02-09 17:40:04,038 | INFO | [82/106] JOY RINE NGERI BANGET!! MOSKOV HAIZ JUGA NGERI!! M... -> 97 comments

  [82/106] JOY RINE NGERI BANGET!! MOSKOV HAIZ JUGA NGERI!! M... -> 97
    -> 174 comments, 167 unique authors

2026-02-09 17:40:07,272 | INFO | [83/106] MENIT 9 END?! CECIL RINZ NGERI BANGET!! FRANCO IDO... -> 174 comments

  [83/106] MENIT 9 END?! CECIL RINZ NGERI BANGET!! FRANCO IDO... -> 174
    -> 42 comments, 40 unique authors

2026-02-09 17:40:09,004 | INFO | [84/106] TIGREAL IDOK MONTAGE DAPET 4?!! MATCH 1 RRQ HOSHI ... -> 42 comments

  [84/106] TIGREAL IDOK MONTAGE DAPET 4?!! MATCH 1 RRQ HOSHI ... -> 42
    -> 31 comments, 26 unique authors

2026-02-09 17:40:10,761 | INFO | [85/106] JOY RINE NGERI BANGET!! DEBUT KEDUA JUNGLER MUDA!!... -> 31 comments

  [85/106] JOY RINE NGERI BANGET!! DEBUT KEDUA JUNGLER MUDA!!... -> 31
    -> 39 comments, 38 unique authors

2026-02-09 17:40:12,413 | INFO | [86/106] SURPRISE PICK HAZLE PAKAI HANZO?!! NGERI BANGET!! ... -> 39 comments

  [86/106] SURPRISE PICK HAZLE PAKAI HANZO?!! NGERI BANGET!! ... -> 39
    -> 26 comments, 25 unique authors

2026-02-09 17:40:13,981 | INFO | [87/106] MATCH PANAS JUAL BELI SERANGAN!!! MATCH 1 RRQ HOSH... -> 26 comments

  [87/106] MATCH PANAS JUAL BELI SERANGAN!!! MATCH 1 RRQ HOSH... -> 26
    -> 16 comments, 16 unique authors

2026-02-09 17:40:15,704 | INFO | [88/106] GRANGER TOY GILAA!!! MPL MATCH 1 RRQ VS NAVI... -> 16 comments

  [88/106] GRANGER TOY GILAA!!! MPL MATCH 1 RRQ VS NAVI... -> 16
    -> 29 comments, 29 unique authors

2026-02-09 17:40:17,316 | INFO | [89/106] MCGOGO!! CLAUDE B3 KARRIE B3 OP?!!... -> 29 comments

  [89/106] MCGOGO!! CLAUDE B3 KARRIE B3 OP?!!... -> 29
    -> 6 comments, 6 unique authors

2026-02-09 17:40:18,854 | INFO | [90/106] HARITH KELRA MANIAC?!! GRAND FINAL BO 7 ONIC ID VS... -> 6 comments

  [90/106] HARITH KELRA MANIAC?!! GRAND FINAL BO 7 ONIC ID VS... -> 6
    -> 17 comments, 17 unique authors

2026-02-09 17:40:20,648 | INFO | [91/106] SELENA SUPERFRINCE ANNOYING BANGET!! GRAND FINAL B... -> 17 comments

  [91/106] SELENA SUPERFRINCE ANNOYING BANGET!! GRAND FINAL B... -> 17
    -> 43 comments, 40 unique authors

2026-02-09 17:40:22,259 | INFO | [92/106] FANNY KINGKONG MENGERIKAN!!! GRAND FINAL BO 7 ONIC... -> 43 comments

  [92/106] FANNY KINGKONG MENGERIKAN!!! GRAND FINAL BO 7 ONIC... -> 43
    -> 10 comments, 10 unique authors

2026-02-09 17:40:23,847 | INFO | [93/106] GAGAL #100JUTOY!! SAVAGE KELRA!! UPPER BRACKET MAT... -> 10 comments

  [93/106] GAGAL #100JUTOY!! SAVAGE KELRA!! UPPER BRACKET MAT... -> 10
    -> 6 comments, 5 unique authors

2026-02-09 17:40:25,314 | INFO | [94/106] GILAKK SANZ!! LOU YI SANZ NGERI BANGET!! UPPER BRA... -> 6 comments

  [94/106] GILAKK SANZ!! LOU YI SANZ NGERI BANGET!! UPPER BRA... -> 6
    -> 10 comments, 10 unique authors

2026-02-09 17:40:26,865 | INFO | [95/106] NOLAN KAIRI MENGGILA!! UPPER BRACKET MATCH 1 ONIC ... -> 10 comments

  [95/106] NOLAN KAIRI MENGGILA!! UPPER BRACKET MATCH 1 ONIC ... -> 10
    -> 29 comments, 28 unique authors

2026-02-09 17:40:28,446 | INFO | [96/106] NOLAN KAIRI MENGGILAA?!! MATCH 1 RRQ HOSHI VS ONIC... -> 29 comments

  [96/106] NOLAN KAIRI MENGGILAA?!! MATCH 1 RRQ HOSHI VS ONIC... -> 29
    -> Fetching full replies for 1 threads...
    -> 97 comments, 92 unique authors

2026-02-09 17:40:30,701 | INFO | [97/106] CLAUDE MUSEUM?!!... -> 97 comments

  [97/106] CLAUDE MUSEUM?!!... -> 97
    -> 78 comments, 70 unique authors

2026-02-09 17:40:32,673 | INFO | [98/106] MODE JONGKOK?! KETEMU EVOS MDL DI RANK BERSAMA PAR... -> 78 comments

  [98/106] MODE JONGKOK?! KETEMU EVOS MDL DI RANK BERSAMA PAR... -> 78
    -> Fetching full replies for 1 threads...
    -> 108 comments, 101 unique authors

2026-02-09 17:40:35,050 | INFO | [99/106] YSS LEVEL 15 MENIT 7 BERSAMA PARTY ANOMALI?!!... -> 108 comments

  [99/106] YSS LEVEL 15 MENIT 7 BERSAMA PARTY ANOMALI?!!... -> 108
    -> 26 comments, 25 unique authors

2026-02-09 17:40:36,565 | INFO | [100/106] FAVIAN ACUUU GAK ADA OBAT KALO MAKEK JOY !!! TEAM ... -> 26 comments

  [100/106] FAVIAN ACUUU GAK ADA OBAT KALO MAKEK JOY !!! TEAM ... -> 26
    -> Fetching full replies for 1 threads...
    -> 61 comments, 57 unique authors

2026-02-09 17:40:38,651 | INFO | [101/106] THIS IS KING ALBERTTT ! TEAM LIQUID ID DI BIKIN GA... -> 61 comments

  [101/106] THIS IS KING ALBERTTT ! TEAM LIQUID ID DI BIKIN GA... -> 61
    -> 68 comments, 64 unique authors

2026-02-09 17:40:40,602 | INFO | [102/106] SUPER DUPER BIG MATCH RRQ HOSHI VS ALTER EGO MATCH... -> 68 comments

  [102/106] SUPER DUPER BIG MATCH RRQ HOSHI VS ALTER EGO MATCH... -> 68
    -> 63 comments, 60 unique authors

2026-02-09 17:40:42,549 | INFO | [103/106] RRQ HOSHI VS ALTER EGO !!! SERU BANGET PERTANDINGA... -> 63 comments

  [103/106] RRQ HOSHI VS ALTER EGO !!! SERU BANGET PERTANDINGA... -> 63
    -> Fetching full replies for 1 threads...
    -> 57 comments, 54 unique authors

2026-02-09 17:40:44,564 | INFO | [104/106] 2 0 SAJA BOSSS !!! EVOS HOLY VS HOME BOIS MATCH 2 ... -> 57 comments

  [104/106] 2 0 SAJA BOSSS !!! EVOS HOLY VS HOME BOIS MATCH 2 ... -> 57
    -> 76 comments, 71 unique authors

2026-02-09 17:40:46,622 | INFO | [105/106] GACOR RETRI ALBERTTT BISA BUAT COMEBACK !!! EVOS H... -> 76 comments

  [105/106] GACOR RETRI ALBERTTT BISA BUAT COMEBACK !!! EVOS H... -> 76
    -> Fetching full replies for 1 threads...
    -> 104 comments, 94 unique authors

2026-02-09 17:40:48,815 | INFO | [106/106] THIS IS SUTSUJIN BROKKK MANIAC !!! RRQ HOSHI VS TE... -> 104 comments

  [106/106] THIS IS SUTSUJIN BROKKK MANIAC !!! RRQ HOSHI VS TE... -> 104
============================================================
Done in 896.3s (14.9 min)

## 6. Data Validation & Export

In [12]:
# === DATA VALIDATION ===
print("=" * 60)
print("DATA VALIDATION")
print("=" * 60)

# Expected columns (the contract for downstream scripts)
EXPECTED_COLUMNS = [
    'comment_id', 'parent_id', 'is_reply', 'comment_text',
    'comment_published_at', 'comment_updated_at',
    'author_channel_id', 'author_display_name',
    'like_count', 'reply_count',
    'channel_subscriber_count', 'channel_video_count',
    'channel_view_count', 'channel_created_at',
    'channel_description_length', 'channel_hidden_subscriber',
    'video_id', 'video_title', 'video_channel_id',
    'video_channel_title', 'video_category_id', 'video_published_at',
    'video_view_count', 'video_like_count', 'video_comment_count',
    'source_channel', 'scrape_date',
]

if len(comments_df) > 0:
    # Check columns
    missing = set(EXPECTED_COLUMNS) - set(comments_df.columns)
    extra = set(comments_df.columns) - set(EXPECTED_COLUMNS)
    
    if missing:
        print(f"  MISSING columns: {missing}")
        logger.error(f"Missing columns: {missing}")
    if extra:
        print(f"  EXTRA columns (will keep): {extra}")
    if not missing:
        print(f"  Column check: PASSED ({len(EXPECTED_COLUMNS)} expected columns present)")

    # Deduplicate by comment_id
    before_dedup = len(comments_df)
    comments_df = comments_df.drop_duplicates(subset=['comment_id'], keep='first')
    after_dedup = len(comments_df)
    print(f"  Dedup comment_id: {before_dedup} -> {after_dedup} (removed {before_dedup - after_dedup})")

    # Null check
    null_text = comments_df['comment_text'].isna().sum()
    null_author = comments_df['author_channel_id'].isna().sum() + (comments_df['author_channel_id'] == '').sum()
    print(f"  Null comment_text: {null_text}")
    print(f"  Empty author_channel_id: {null_author}")

    # Reorder columns
    final_cols = [c for c in EXPECTED_COLUMNS if c in comments_df.columns]
    extra_cols = [c for c in comments_df.columns if c not in EXPECTED_COLUMNS]
    comments_df = comments_df[final_cols + extra_cols]

    print(f"  Final shape: {comments_df.shape}")
    logger.info(f"Validation passed. Shape: {comments_df.shape}")
else:
    print("  No data to validate.")

2026-02-09 17:49:10,590 | INFO | Validation passed. Shape: (57991, 27)

============================================================
DATA VALIDATION
============================================================
  Column check: PASSED (27 expected columns present)
  Dedup comment_id: 59165 -> 57991 (removed 1174)
  Null comment_text: 0
  Empty author_channel_id: 0
  Final shape: (57991, 27)

In [13]:
# === EXPORT ===
comments_file = CONFIG['output_dir'] / f'{OUTPUT_FILENAME}.csv'
stats_file = CONFIG['output_dir'] / f'{OUTPUT_FILENAME}_video_stats.csv'

if len(comments_df) > 0:
    comments_df.to_csv(comments_file, index=False, encoding='utf-8-sig')
    size_mb = comments_file.stat().st_size / 1024 / 1024
    print(f"Dataset saved: {comments_file}")
    print(f"  Rows: {len(comments_df):,} | Size: {size_mb:.2f} MB")
    logger.info(f"Exported {len(comments_df)} comments to {comments_file}")
else:
    print("No comments collected.")

stats_df.to_csv(stats_file, index=False, encoding='utf-8-sig')
print(f"Video stats saved: {stats_file}")

2026-02-09 17:49:13,375 | INFO | Exported 57991 comments to output\dataset_spamshield.csv

Dataset saved: output\dataset_spamshield.csv
  Rows: 57,991 | Size: 26.33 MB
Video stats saved: output\dataset_spamshield_video_stats.csv

## 7. Summary & Audit Report

In [14]:
# === SUMMARY ===
print("=" * 60)
print("SCRAPING SUMMARY")
print("=" * 60)

total = len(stats_df)
success = len(stats_df[stats_df['status'] == 'success']) if 'status' in stats_df.columns else 0
print(f"\nVideos: {success}/{total} successful")

if len(comments_df) > 0:
    print(f"\nComments:")
    print(f"  Total           : {len(comments_df):,}")
    print(f"  Top-level       : {len(comments_df[~comments_df['is_reply']]):,}")
    print(f"  Replies         : {len(comments_df[comments_df['is_reply']]):,}")
    print(f"  Unique authors  : {comments_df['author_channel_id'].nunique():,}")
    print(f"  Unique videos   : {comments_df['video_id'].nunique():,}")

    # Per-source breakdown
    if 'source_channel' in comments_df.columns:
        print(f"\nPer source channel:")
        source_summary = comments_df.groupby('source_channel').agg(
            comments=('comment_id', 'count'),
            videos=('video_id', 'nunique'),
            unique_authors=('author_channel_id', 'nunique'),
        ).sort_values('comments', ascending=False)
        for source, row in source_summary.iterrows():
            print(f"  [{source}]: {row['comments']:,} comments, {row['videos']} videos, {row['unique_authors']:,} authors")

    # Quality
    empty = comments_df['comment_text'].isna().sum() + (comments_df['comment_text'] == '').sum()
    dupes = comments_df['comment_id'].duplicated().sum()
    print(f"\nQuality:")
    print(f"  Empty comments  : {empty}")
    print(f"  Duplicate IDs   : {dupes}")

    print(f"\nColumns ({len(comments_df.columns)}):")
    for col in comments_df.columns:
        print(f"  {col}")

logger.info("=== SCRAPING COMPLETE ===")
logger.info(f"Total comments: {len(comments_df)}")
logger.info(f"Videos success: {success}/{total}")

2026-02-09 17:49:15,550 | INFO | === SCRAPING COMPLETE ===
2026-02-09 17:49:15,550 | INFO | Total comments: 57991
2026-02-09 17:49:15,550 | INFO | Videos success: 106/106

============================================================
SCRAPING SUMMARY
============================================================

Videos: 106/106 successful

Comments:
  Total           : 57,991
  Top-level       : 43,160
  Replies         : 14,831
  Unique authors  : 39,652
  Unique videos   : 106

Per source channel:
  [FerryIrwandi]: 23,983 comments, 6 videos, 18,960 authors
  [MasterChef]: 20,843 comments, 14 videos, 11,139 authors
  [FrostDiamond]: 5,984 comments, 10 videos, 4,707 authors
  [JebreetMedia]: 2,522 comments, 19 videos, 1,940 authors
  [ML]: 1,747 comments, 21 videos, 1,246 authors
  [XIN]: 1,313 comments, 25 videos, 1,186 authors
  [RaymondChin]: 933 comments, 1 videos, 824 authors
  [PUBG]: 666 comments, 10 videos, 555 authors

Quality:
  Empty comments  : 11
  Duplicate IDs   : 0

Columns (27):
  comment_id
  parent_id
  is_reply
  comment_text
  comment_published_at
  comment_updated_at
  author_channel_id
  author_display_name
  like_count
  reply_count
  channel_subscriber_count
  channel_video_count
  channel_view_count
  channel_created_at
  channel_description_length
  channel_hidden_subscriber
  video_id
  video_title
  video_channel_id
  video_channel_title
  video_category_id
  video_published_at
  video_view_count
  video_like_count
  video_comment_count
  source_channel
  scrape_date

In [15]:
# === PREVIEW DATA ===
if len(comments_df) > 0:
    print("Sample: Comment text")
    display(comments_df[[
        'comment_text', 'author_display_name',
        'like_count', 'is_reply', 'source_channel',
    ]].head(10))

    print("\nSample: Channel metadata")
    display(comments_df[[
        'author_display_name',
        'channel_subscriber_count', 'channel_video_count',
        'channel_view_count', 'channel_created_at',
        'channel_description_length', 'channel_hidden_subscriber',
    ]].drop_duplicates(subset='author_display_name').head(10))

Sample: Comment text

,comment_text,author_display_name,like_count,is_reply,source_channel
0,Assalamualaikum bang tolong ijin nin pengguna ...,@Shiro-danji,0,False,ML
1,re almeng Suramadu olanya itunya,@DaffaaPR,2,False,ML
2,Jaringan mu ngelag,@adamardiansyah5761,0,False,ML
3,Min kok skin starwars gw kok ilang?,@boys.252,0,False,ML
4,"Baca patch bro, jgn minim literasi",@OnlyRiff,0,True,ML
5,@OnlyRiff gw blm download data patch nya aja ...,@boys.252,0,True,ML
6,Buat moonton pliss lah Hero gue jangan di ruba...,@raysahetapy6474,1,False,ML
7,Tinggal konten gloo revaml,@Awn98,0,False,ML
8,Skil satu nya jadi bagus,@HalimahElin-ob4lf,0,False,ML
9,"ini baru cewe , daripada sebelum di revamp kay...",@dreammashup2214,1,False,ML

Sample: Channel metadata

,author_display_name,channel_subscriber_count,channel_video_count,channel_view_count,channel_created_at,channel_description_length,channel_hidden_subscriber
0,@Shiro-danji,1,1,567,2023-03-02T08:21:51.63267Z,216,False
1,@DaffaaPR,2,0,0,2020-07-27T09:10:36.078816Z,149,False
2,@adamardiansyah5761,8,3,1582,2013-06-17T04:53:11Z,0,False
3,@boys.252,8,3,38,2022-11-09T10:24:33.17254Z,0,False
4,@OnlyRiff,291,2,144,2021-02-26T16:08:45.913963Z,22,False
6,@raysahetapy6474,0,0,0,2021-09-20T10:38:57.996369Z,26,False
7,@Awn98,0,3,19,2016-10-31T12:48:34Z,0,False
8,@HalimahElin-ob4lf,0,0,0,2024-06-22T10:33:27.069009Z,0,False
9,@dreammashup2214,97,157,26230,2016-01-16T08:11:44Z,0,False
10,@INSol-T13,71,25,14998,2023-06-23T04:29:35.06088Z,26,False

In [16]:
# === VIDEO STATS ===
print("Video Statistics:")
display(stats_df)

Video Statistics:

,video_id,video_title,video_channel_title,source_channel,video_comment_count_api,comments_scraped,status
0,c6C8RgNb-6c,Hero Spotlight | Kimmy | Hoverjet Outrider | M...,Mobile Legends: Bang Bang Indonesia,ML,95,95,success
1,b7pLYP7ihhg,MLBB × NARUTO | Pratinjau Konten Kustom | Mobi...,Mobile Legends: Bang Bang Indonesia,ML,88,88,success
2,29FqHi9rkDQ,🔴 LIVE | MPL ID S15 | Regular Season Hari 3 Mi...,Mobile Legends: Bang Bang Indonesia,ML,85,85,success
3,T53xSsP35yk,🔴 LIVE | MPL ID S15 | Regular Season Hari 1 Mi...,Mobile Legends: Bang Bang Indonesia,ML,44,44,success
4,IMmeX4FuUQM,🔴LIVE | MDL ID S11 | Progressive Round | Hari ...,Mobile Legends: Bang Bang Indonesia,ML,15,15,success
...,...,...,...,...,...,...,...
101,vF63kGOJaAo,SUPER DUPER BIG MATCH RRQ HOSHI VS ALTER EGO M...,XINNN,XIN,68,68,success
102,Wm9uw_KmzEo,RRQ HOSHI VS ALTER EGO !!! SERU BANGET PERTAND...,XINNN,XIN,63,63,success
103,tCIWC4eMugs,2 0 SAJA BOSSS !!! EVOS HOLY VS HOME BOIS MATC...,XINNN,XIN,57,57,success
104,_u69H8dC_M0,GACOR RETRI ALBERTTT BISA BUAT COMEBACK !!! EV...,XINNN,XIN,76,76,success
105,Ml8252hTy1c,THIS IS SUTSUJIN BROKKK MANIAC !!! RRQ HOSHI V...,XINNN,XIN,104,104,success